playcanvas/attribute-parser

src/parsers/script-parser.js
test/tests/valid/curve.test.js

This PR fixes an issue with parsing curve attributes when specified without a default value.
Currently the default behaviour is to return `{ default: []}` when no default value is defined in the code. This is inconsistent with current script parsing which expects the `default` to be excluded from the response.
This PR fixes this, so that the `default` value is not included. This fixes an upstream UI issue with the curve editor with empty  arrays.  Tests have been updated to reflect this correct behaviour

Fix default value for curve attributes

---

src/global.types.js
src/index.js
test/fixtures/asset.invalid.js
test/fixtures/program.valid.js
test/tests/valid/program.test.js

This PR adds support for parsing code that contains explicit external http/s imports.
Previously the following would fail in the parser because the types for the external modules could not be determined
```javascript
import { Script } from 'playcanvas';
import confetti from "https://esm.sh/canvas-confetti@1.6.0"
export class Example extends Script {
initialize() {
confetti();
}
}
```
https/s module imports are now implicitly treated as `any`, which allows the parser to effectively ignore them. This fixes #2. Test also added

Support http/s imports

---

src/utils/ts-utils.js
test/fixtures/program.valid.js

Fixes an issue parsing a Script where exporting both an enum and Script would fail in the parser
```javascript
// This would fail
/** @enum {number} */
import { Script } from 'playcanvas';
export const MyEnum = { value: 0 };
export class MyScript extends Script {};
```
Included the condition in the `./program.valid.js` test

Fixes Enum check

---

src/index.js

Added check for missing jsdoc tag. Fixes #10

Added check incase of missing jsdoc tag

---

src/utils/tag-utils.js
test/fixtures/program.valid.js
test/tests/valid/program.test.js

Ensures any errors reported whilst validating jsdoc tags  ie `@range`, `@precision` and `@step` contain the correct relevant errors for the target file and not other semantic program errors unrelated to the current file. Fixes #13 
Includes test coverage
Also adds some better code documentation.

Scoped Tag Validation

---

package.json
src/parsers/attribute-parser.js
src/parsers/script-parser.js
src/utils/ts-utils.js
test/fixtures/enum.valid.js

Adds support for enum attributes by reference. Fixes #12 .
Both the following using literal and reference are now supported. Tests updated to include both use cases.
```javascript
import { Script } from 'playcanvas'
/** @enum {number} */
const Lights = {
ON: 1,
OFF: 0,
UNKNOWN: 0.5
}
class Hack extends Script {
/**
* @attribute
* @type {Lights}
*/
ambient = Lights.OFF
/**
* @attribute
* @type {Lights}
*/
spec = 0
}
export { Hack };
```

Adds Support for Enum refs

---

package-lock.json
package.json
src/parsers/attribute-parser.js
test/fixtures/enum.valid.js
test/tests/valid/enum.test.js

Fixes an issue with string enums that would return an incorrect value. Previously when parsing the following script 
```javascript
/** @enum */
const StringEnum = { A = "a"  }
class MyScript {
/** 
* @attribute
* @type {StringEnum}
*/
str;
}
```
The parser would return this enum schema `{ enum: [{ A : '"a"'}]}` (notice the 'a' wrapped in nested quotations)
This PR fixes this and  adds missing tests around this case.

String Enum Fix

---

src/parsers/attribute-parser.js
src/parsers/script-parser.js
src/utils/ts-utils.js
test/fixtures/asset.invalid.ts
test/fixtures/asset.valid.ts
test/fixtures/enum.valid.js
test/fixtures/enum.valid.ts
test/fixtures/json.valid.ts
test/tests/valid/asset.test.js
test/tests/valid/checkbox.test.js
test/tests/valid/enum.test.js
test/tests/valid/json.test.js

This PR adds support for declaring script attribute via TypeScript. Tests included
```typescript
import { Script } from 'playcanvas'
export class My extends Script {
/** @attribute */
num : Number = 10
/** @attribute */
str : String = 'hello'
} 
```
It also adds supports  for declaring `enums` and `interfaces`
```typescript
import { Script } from 'playcanvas'
enum Options { OFF, ON, UNKNOWN }
interface Enemy {
speed : Number
boost: Boolean
}
export class My extends Script {
/** @attribute */
opts : Options
/** @attribute */
enemies : Enemy[]
} 
```

TypeScript Support

---

package-lock.json
package.json
src/index.js

Previously the parser would be initialized with a directory path from which to load types
```javascript
new Parser().init('/path/to/types/dir/');
```
The dom types are in seperate files, which would result in ~80 network request to various files.
This PR extends the api so that a path to a single file can be used instead, which allows for a single file to be loaded that represents all the types neccessary
```javascript
new Parser().init('/path/to/types/dir/lib.d.ts');
```

Support Single Types file

---

src/parsers/script-parser.js
src/utils/ts-utils.js
test/fixtures/example.dep.js
test/fixtures/inherit.valid.js
test/tests/valid/inherit.test.js

This PR adds support to extend ESM Scripts in relative modules and inherit their attributes. 
This means you can declare a base class in one file, extend it in another and inherit it's attributes.
Fixes #20. Tests included.
```javascript
// "./rotator.js"
import { Script } from 'playcanvas';
export class Rotator extends Script {
/**
* @attribute
* You can now set the `speed`property dynamically in the editor
*/
speed = 2;
update(dt){
this.entity.rotateLocal(0, this.speed * dt, 0)
}
}
// "./double-fast-rotator.mjs"
import {Rotator} from './rotator.mjs'
export class DoubleFastRotator extends Rotator {
update(dt){
this.entity.rotateLocal(0, this.speed * dt * 2, 0)
}
}
```

Support Inherited Attributes across files

---

src/index.js
test/tests/valid/empty.test.js

Fixes a reported issue where parsing an empty file would throw an error. This is likely an upstream problem with typescript/vfs, but this PR instead gracefully handles this edge case by returning early.
Includes tests for empty files

Allow empty files

---

package-lock.json
package.json
src/parsers/attribute-parser.js
src/parsers/script-parser.js
src/utils/attribute-utils.js
src/utils/ts-utils.js

This PR refactors to remove the dependancy on **`@microsoft/tsdoc`**.  This has a number of benefits
- Reduces code complexity
- Reduces bundled size
- Improves parsing time (~10%)
- Removes [circular dependancy](https://github.com/playcanvas/editor-ui/blob/6260865a601e6f4741643fa741246c201ec5430c/rollup.config.mjs#L125-L138) which should help bundling

Removes @microsoft/tsdoc dependancy

---

src/parsers/script-parser.js
test/fixtures/conditional.valid.js
test/tests/valid/conditional.test.js

This PR introduces support for conditional attributes in the script parser. The main changes include adding new attributes, updating the parser to handle these attributes, and adding tests to ensure the functionality works as expected.
See https://github.com/playcanvas/editor/issues/1196 for community discussion.
See https://github.com/playcanvas/editor-ui/pull/499 for editor context
PR also includes tests [`test/tests/valid/conditional.test.js`](diffhunk://#diff-5c76449d40ac5590b40ce7c2a3e8e69f8ade27513e178e615de460b8062e0e11R1-R45)

Support `@visibleif` and `@enabledif` tags

---

package-lock.json
package.json
src/parsers/attribute-parser.js
test/fixtures/enum.valid.js
test/fixtures/enum.valid.ts
test/tests/valid/enum.test.js

Adds support for declaring enums keys as string literals. 
Test included. Fixes https://github.com/playcanvas/editor/issues/1255
```javascript
const MyEnum = {
"Some String": 10
}
```
and in TS
```typescript
enum MyEnum {
"Some String": 10
}
```

Feat string keys

---

src/utils/ts-utils.js
test/fixtures/misc.valid.js
test/tests/valid/misc.test.js

Fixes an issue where accessor attributes defined as getter/setters were not parsed and silently ignored.
Tests included. Fixes #34 .
```javascript
class X extends Script {
// This now works!
/** @attribute **/
get someAttr() { }
set someAttr() { }
// This works too
/** @attribute **/
set someAttr() { }
get someAttr() { }
} 
```

Fixed issue parsing accessor attributes in reverse order

---

package-lock.json
package.json
src/index.js
test/fixtures/program.valid.js
test/tests/valid/program.test.js

This pull request introduces a minor version update and enhances the functionality of the JSDoc parser to support custom script names. It also includes corresponding updates to test files to validate the new functionality.
* [`src/index.js`](diffhunk://#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R146-R165): Added a new helper function `isScriptNameMember` to identify static `scriptName` properties in class declarations. Updated the logic to use the `scriptName` property as the class name if it exists.
* [`test/fixtures/program.valid.js`](diffhunk://#diff-1ca23b0c0f21dada26d396c4bd6133d469286dd53ea0957987a8da94b7b8d851R9-R10): Added a `static scriptName` property to the `Example` class to test the new functionality.
* …

Parse static scriptName field

---

src/parsers/script-parser.js
src/utils/ts-utils.js
test/fixtures/json.valid.js
test/fixtures/json.valid.ts
test/tests/valid/json.test.js

This PR updates the parsing to handle nested attributes better
**Before (nested attributes require @interface):**
```jsx
import { Script } from 'playcanvas'
/** @interface */
class JSON {
/** 
* Some important description
* @range [0, 10] 
*/
num = 10
}
class Test extends Script {
/** 
* @attribute 
* @type {JSON}
*/
json
}
```
Object literals were supported but their metadata like `@range` or description were not included (See #38)
**This has now been updated to support object literals:**
```jsx
import { Script } from 'playcanvas'
class Test extends Script {
/** @attribute */
json = {
/** 
* Some important description
* @range [0, 10] 
*/
num = 10
}
}
```
Tests included. Fixes #38

Support inline object literal attributes

---

src/parsers/attribute-parser.js
test/fixtures/misc.valid.js
test/tests/valid/json.test.js
test/tests/valid/misc.test.js

Returns the full attribute description without clipping to the first full stop.
Fixes #39. Tests updated

Feat multi sentence description

---

src/index.js
src/utils/attribute-utils.js
test/fixtures/intellisense.valid.js
test/tests/valid/intellisense.test.js

This PR ensures static class members are not returned in the `getAttributes()` function. This ensures the editor does not recommend promoting static fields to attributes. Fixes https://github.com/playcanvas/editor/issues/1310
- Introduced isStaticMember function to check for static properties in TypeScript nodes.
- Updated JSDocParser to use isStaticMember for identifying static scriptName properties.
- Enhanced tests to ensure static members are not returned in the parsed data.

Ignore static members in `getAttributes`

---

src/parsers/attribute-parser.js
test/fixtures/numeric.valid.js
test/tests/valid/numeric.test.js

PR fixes the following issue:
When a summary description was included after a `@range` tag, the parsing would fail, with an invalid error
```js
/**
* @range [0, 1]
* A summary description after the range tag would be flagged as an error
*/
v = 1
```
**Fix**
Ensure trailing comments are not included when parse the range contents. Tests included

Fix range error

---

src/parsers/attribute-parser.js
src/utils/ts-utils.js
test/fixtures/literal-unions.invalid.js
test/fixtures/literal-unions.valid.js
test/tests/invalid/literal-unions.test.js
test/tests/valid/enum.test.js
test/tests/valid/literal-unions.test.js

This PR fixes a bug parsing literal union types.
```typescript
layout:
| "joystick-joystick"
| "joystick-touch"
| "touch-joystick"
| "touch-touch"
```
It now correctly supports homogenous literal unions and logs an error when using mixed unions
```typescript
mixedUnion: 1 | "two"
mixedPrimitiveUnion: string | boolean
```
This fixes a parsing error with the [`camera-controls.js`](https://github.com/playcanvas/engine/blob/377604413062302fe39b07558c354929d2eeb791/scripts/esm/camera-controls.mjs#L575) whose type was actually narrowed to the [`DualGestureSource`](https://api.playcanvas.com/engine/classes/DualGestureSource.html#layout)
Tests included. Fixes #19 
- Updated `getType` function to identify mixed literal unions and return an `isMixedUnion` flag.
- Modified `getNodeAsAttribute` to …

Support Literal Unions

---

src/index.js
src/parsers/attribute-parser.js
src/parsers/parsing-error.js
src/parsers/script-parser.js
test/tests/valid/export.test.js

This PR enhances error reporting and context handling throughout the attribute and script parsing logic. The main focus is on propagating `scriptName` and `attributeName` information into parsing errors, making debugging and error tracing much easier. Additionally, some minor bug fixes and improvements are included in how attribute positions are calculated.
- Refactored `ParsingError` to include additional context in error messages, improving clarity on the source of errors.
- Modified `JSDocParser` to pass `scriptName` during attribute extraction, ensuring consistent error reporting across scripts.
- Enhanced tests to verify the presence of `scriptName` in error outputs, ensuring comprehensive error tracking.

Additional name and script ref in error reporting

---

.github/workflows/ci.yml
.github/workflows/publish.yml
README.md
package.json

- Updated README
- Updated package json and workflows to match template repo

Structure fixes
